/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_test;

import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Client client;
        try {
            client = new Client();
            client.close();
        } catch (Exception e) {
            //TODO: handle exception
        }

        // @Nullable Object obj = new Object("Nullable");
        // @NonNull Object nnobj = new Object("NonNull");

        // nnobj = null;

        // System.out.println(obj.toString());
    }
}
